trigger:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: 'windows-latest'

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
  - group: cancerconnect-api-dev-variables
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - group: cancerconnect-api-staging-variables

stages:
- stage: Build
  displayName: 'Build and Validate'
  jobs:
  - job: CI
    displayName: 'Continuous Integration Job'
    steps:
    - template: pipelines/templates/build-template.yml
